
# Test file generated by AddTests.py
import pytest
from otrade.utils.auth import login, logout


def test_login():
    result = login()
    assert result == False


def test_logout():
    result = logout()
    assert result == False
