
# Test file generated by AddTests.py
import pytest
from otrade.config.config import RH_USERNAME, RH_PASS, ENV_EXCEPTION


def test_get_quote():
    assert RH_USERNAME == ENV_EXCEPTION
    assert RH_PASS == ENV_EXCEPTION



